### ISSUE TITLE
Create a new test instance

### ISSUE THREAD

**Issue by vinzBad** [CZ-NIC/python-rt#35]
I just saw that you lost access to your demo instance (#28 ). I'm thinking of creating one for this project.  Do you have any requirements?

My requirement would be to remove the test instance credentials from source and instead injecting them with one of the methods specified here: https://docs.travis-ci.com/user/best-practices-security/ I could implement this in a PR, but we'd need a private communication channel so I can send you the passwords.

**Comment by vinzBad** [comment]
One could also install RT in .travis-ci.yml. What do you think?

**Comment by sebix** [comment]
First, thanks for tackling this issue!

I also did think about the second option, to install RT in the test environment, but did not work on it because I didn't have the time to actually do it. I can imagine, that the installation procedure does take some time, so the tests are quite long-running. On the other hand, there are not a lot test runs anyway.

For tests run locally/not on travis, the first solution would be better, and allows easier development.

@e3rd has admin privileges here, so he could configure the credentials in this repository.

**Comment by e3rd** [comment]
Hello @vinzBad , I am gladly willing to edit any file you'd like. Just tell me what to do :D
